### Day 1: NumPy

Today the goal is to introduce some commonly used numpy functions but also develop your ability to read documentation. 

Useful references: 
* [Official NumPy reference ](https://numpy.org/doc/1.18/reference/index.html)
* [Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

#### Why numpy?
Good set of array operations. Basis for many Python packages for image processing, games libraries, simulations, machine learning packages, graphics libraries.

In [72]:
#imports: if you want to use external functions, you need to import them first
#conventional way of importing numpy
import numpy as np

Last week we saw lists. Let's have a quick look at some list operations.Particularly: 
* Adding elements to an existing list
* Storing elements of a different type
* Updating the value of an element

In [73]:
#list operations
#for example, we can define a list that contains information about a student, called Chris who is 16 and is from Glasgow.
#Chris is friends with Ben, Tom, and Alex
#We've created a list

student1 = ["Chris",16,"Glasgow",['Ben',"Tom","Alex"]]

#Lists are mutable. We can update that Chris now lives in Edinburgh
student1[2] = "Edinburgh"
print (student1)

['Chris', 16, 'Edinburgh', ['Ben', 'Tom', 'Alex']]


In [74]:
#Since Chris moved to Edinburgh, he made a new friend
student1[3].append("Jane")
print (student1)

['Chris', 16, 'Edinburgh', ['Ben', 'Tom', 'Alex', 'Jane']]


#### On ndarrays
(n dimensional arrays)

Last week we talked about lists, however arrays are quite different from lists:

* fixed, predefined size/shape
* all elements have the same type (remember in lists we can have items of different types)
* they can only hold numbers (typically integers or floating-point)
* multidimensional
* Cannot extend or resize after creating arrays, so must create a new array and copy over old elements
* arrays are mutable: the values can be changed after creation


ndarrays can have different dimensions. An array with more than 2 dimensions is usually called a tensor. Tensors are often used to represent images. 




In [28]:
#generate some numbers
#np.arrange can take up to 3 arguments, np.arange(end)
x = np.arange(6)
print (x)

#update an element of the array
x[2] = 10

print (x)

[0 1 2 3 4 5]
[ 0  1 10  3  4  5]


In [32]:
#Your turn: Using np.arange create an 1D array from 0-30 (inclusive), stepping by 2.



In [29]:
#creating an array: we pass lists
x = np.array([[1, 2, 3], [4, 5, 6]])

print (x.size)
print (x.shape)
print (x.dtype)

6
(2, 3)
int64


#### Blank and random arrays
In some situations, it might be useful to create an array with a specific shape and set all elements to a specific value. This can be done in a few ways but essentially all methods below just call np.empty(shape) to create a new array and then filling it with a given value. 

* np.zeros(shape): initialises all elements to 0
* np.ones(shape): inits all elements to 1
* np.full(shape, value):  inits all elements to a value


Some algorithms work with random initialisations. Luckily, numpy provides a range of functions to allow us to do this.
* np.random.randint(a,b,shape): array with uniform random integers between a and b
* np.random.uniform(a,b,shape): array with uniform floating point numbers between a and b

#### Your turn now!!!
Use numpy to create the following: 
* a 7 x 8 matrix of all ones
* a 3 element vector, with all elements equal to np.pi
* a 1 x 2 x 5 element array of all ones.

In [42]:
#Your code goes here

#### Slicing and indexing

This can be quite similar to lists. Negative indexing is also supported.Let's look at some examples.

In [54]:
x = np.array([[4,5,6,10,12,16],[7,8,9,10,3,2],[20,19,18,17,16,15]])
print (x.shape)

(3, 6)


In [55]:
x[-1,-1] #last row, last columns

15

In [56]:
x[0,2]

6

In [65]:
x[:,0:4] #all rows, first 4 columns

array([[ 4,  5,  6, 10],
       [ 7,  8,  9, 10],
       [20, 19, 18, 17]])

#### Boolean indexing
Sometimes we might want to subset based on a condition

In [41]:
onezero = np.array([[0,1,0], [1, 1, 1], [1, 1, 1]])
subset = onezero[onezero==0]

#### Your turn now!!!
Using what you've learned so far and the numpy documentation. 

Create: 

* an array of evenly spaced numbers between -1 and 1
* create two 1D arrays of the same length and stack them (vertically and then horizontally)

In [64]:
#Your code here: